title: Payments and Plans
description: Example.com
template:
  repo: payments-and-plans-template
  name: payments-and-plans
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
